### ISSUE TITLE
Great Code!

### ISSUE THREAD

**Issue by JaeDukSeo** [DuaneNielsen/DeepInfomaxPytorch#2]
amazing! were you able to get up to 69 accuracy? just asking

**Comment by DuaneNielsen** [comment]
Thanks, no not yet.  Been busy working on 2D physics sims for an AI project.

I need to compare my code to the reference code, then try tweaking and testing.

Check out the linked project from the README.  I think that project has correct results.

**Comment by JaeDukSeo** [comment]
Amazing thank u!
