### ISSUE TITLE
Questions about loss functions

### ISSUE THREAD

**Issue by TulsiJain** [DuaneNielsen/DeepInfomaxPytorch#4]
Thanks for the amazing code. 
I was wondering why there is no `log` term with in `LOCAL = (Em - Ej) * self.beta; 
GLOBAL = (Em - Ej) * self.alpha` I think there should be a log term with Em. 

EJ[Tω(x, y)] − log EM[eTω(x,y)], And For EJ why direct expectation is taken rather than of exponent. 

Thanks in advance!

**Comment by DuaneNielsen** [comment]
Think you might have answered your own question there :)

exp(log(x)) = x

normally log and exp are used for numerical stability in calculations.
It's a design choice.

On Sun, Apr 14, 2019 at 6:51 AM Tulsi Jain <notifications@github.com> wrote:

> *CAUTION: This email originated from outside of Broadcom. Do not click
> links or open attachments unless you recognize the sender and know the
> content is safe.*
>
> Thanks for the amazing code.
> I was wondering why there is no log term with in LOCAL = (Em - Ej) *
> self.beta; GLOBAL = (Em - Ej) * self.alpha I think there should be a log
> term with Em.
>
> EJ[Tω(x, y)] − log EM[eTω(x,y)], And For EJ why direct expectation is
> taken rather than of exponent.
>
> Thanks in advance!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_DuaneNielsen_DeepInfomaxPytorch_issues_4&d=DwMFaQ&c=_hRq4mqlUmqpqlyQ5hkoDXIVh6I6pxfkkNxQuL0p-Z0&r=OXK0v8FaD9soLy02fcZZT9gC57Fd39XmOwdHn8UlmOo&m=-F1sUxSeaYpgn1NufsvYiIg5qaOiYTqMrn3umC0q_2M&s=jMBWuGwS2THCxwUsaLwgW4FvbpfPg6HxMoq4U2ftfXE&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AKjsLM-5FlEhAdv5nntTOOG4ZCWjeTTiDdks5vgzI8gaJpZM4cuoPq&d=DwMFaQ&c=_hRq4mqlUmqpqlyQ5hkoDXIVh6I6pxfkkNxQuL0p-Z0&r=OXK0v8FaD9soLy02fcZZT9gC57Fd39XmOwdHn8UlmOo&m=-F1sUxSeaYpgn1NufsvYiIg5qaOiYTqMrn3umC0q_2M&s=I79Ly9LL6UZewfCeYsMR54bZs927nC5eZPoFpRFNtCo&e=>
> .
>


-- 
Duane
Broadcom
480 760 1559

**Comment by TulsiJain** [comment]
oh ya! thanks
