### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\data\\deepinfomax\\models\\run5/encoder860.wgt'

### ISSUE THREAD

**Issue by haohuazhu** [DuaneNielsen/DeepInfomaxPytorch#5]
sorry,i didn't find the file 
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\data\\deepinfomax\\models\\run5/encoder860.wgt'

**Comment by DuaneNielsen** [comment]
Yeah, thats one of my pretrained models.  Just train your own model and it will all be good.

**Comment by AtomicTing** [comment]
How do I train my model？

**Comment by AtomicTing** [comment]
> sorry,i didn't find the file
> FileNotFoundError: [Errno 2] No such file or directory: 'c:\data\deepinfomax\models\run5/encoder860.wgt'

I also encountered the same problem as you. How did you solve it？
